# Generated by Django 2.0 on 2018-05-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0006_auto_20180505_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='playback',
            field=models.FileField(upload_to='media/'),
        ),
    ]
