# Generated by Django 2.0 on 2018-05-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0008_beat_producer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('service', models.CharField(choices=[('SHOOTING', 'Shooting'), ('RECORDING', 'Recording'), ('PHOTO-SHOOTING', 'Photo-Shooting')], max_length=25)),
                ('phone', models.IntegerField()),
                ('alternative_phone', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='beat',
            name='genre',
            field=models.CharField(choices=[('BONGO', 'Bongo'), ('GOSPEL', 'Gospel'), ('REGGAE', 'Reggae'), ('HIPHOP', 'Hiphop'), ('BLUES', 'Blues'), ('R & B', 'R & B'), ('ROCK', 'rock'), ('SOUND TRACK', 'Sound_Track')], max_length=25),
        ),
    ]
