# Generated by Django 2.0 on 2018-05-07 15:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0009_auto_20180507_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='from_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='session',
            name='to_date',
            field=models.DateTimeField(),
        ),
    ]
