# Generated by Django 2.0 on 2018-05-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0010_auto_20180507_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='from_date',
            field=models.DateTimeField(),
        ),
    ]
