# Generated by Django 2.0 on 2018-05-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0011_auto_20180507_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
